# Generated by Django 4.1.7 on 2023-02-20 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField(blank=True, null=True)),
                ("name", models.TextField(blank=True, null=True)),
                ("lastname", models.TextField(blank=True, null=True)),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("date", models.DateTimeField(blank=True, null=True)),
                (
                    "marks",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("role", models.TextField(blank=True, null=True)),
                ("searchtxt", models.TextField(blank=True, null=True)),
                ("searchrole", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClassRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                (
                    "lessons",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("slug", models.SlugField(blank=True, null=True)),
                (
                    "student",
                    models.ManyToManyField(
                        blank=True, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
