# Generated by Django 4.1.7 on 2023-02-20 00:55

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0002_classroom"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="searchrole",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="searchtxt",
            field=models.TextField(blank=True, null=True),
        ),
    ]
